name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install OS dependencies
        run: ci/install-os-dependencies.sh
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install
        run: yarn install --immutable
      - name: Fix permission for test fixtures
        if: runner.os == 'Linux'
        run: chmod --recursive g-w test/fixtures
      - name: Test
        run: yarn test
        env:
          DEBUG: 'electron-installer-debian'
